#!/usr/bin/env python3

import argparse

__version__ = "0.0"


def _parse_arguments():
    parser = argparse.ArgumentParser(
        description="Download VOT Challenge data sequences."
    )
    parser.add_argument(
        "--version",
        action="version",
        version=__version__,
        help="Display the version, and exit.",
    )
    parser.add_argument(
        "dataset",
        choices=["all", "2013", "2014", "2015", "2016", "2017", "2018"],
        default="all",
        help="The dataset(s) to download. Acceptable values are 'all', or the "
        "years 2013 through 2018. 'All' takes precedence and will download all "
        "datasets.",
        metavar="dataset",
        nargs="*",
    )
    return vars(parser.parse_args())


if __name__ == "__main__":
    arguments = _parse_arguments()
    print(arguments)
