#!/usr/bin/env python3

"""This is a script to download OTB data sets."""

import argparse
import os
import shutil
import zipfile

import wget

__version__ = "1.0"


BACKGROUND_CLUTTER = "background_clutter"
DEFORMATION = "deformation"
FAST_MOTION = "fast_motion"
ILLUMINATION_VARIATION = "illumination_variation"
IN_PLANE_ROTATION = "in_plane_rotation"
LOW_RESOLUTION = "low_resolution"
MOTION_BLUR = "motion_blur"
OCCLUSION = "occlusion"
OUT_OF_PLANE_ROTATION = "out_of_plane_rotation"
OUT_OF_VIEW = "out_of_view"
SCALE_VARIATION = "scale_variation"

SEQUENCES = {
    "Basketball": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        ILLUMINATION_VARIATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Biker": [
        FAST_MOTION,
        LOW_RESOLUTION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Bird1": [DEFORMATION, FAST_MOTION, OUT_OF_VIEW],
    "Bird2": [
        DEFORMATION,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "BlurBody": [
        DEFORMATION,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        SCALE_VARIATION,
    ],
    "BlurCar1": [FAST_MOTION, MOTION_BLUR],
    "BlurCar2": [FAST_MOTION, MOTION_BLUR, SCALE_VARIATION],
    "BlurCar3": [FAST_MOTION, MOTION_BLUR],
    "BlurCar4": [FAST_MOTION, MOTION_BLUR],
    "BlurFace": [FAST_MOTION, IN_PLANE_ROTATION, MOTION_BLUR],
    "BlurOwl": [FAST_MOTION, IN_PLANE_ROTATION, MOTION_BLUR, SCALE_VARIATION],
    "Board": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        MOTION_BLUR,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Bolt": [DEFORMATION, IN_PLANE_ROTATION, OCCLUSION, OUT_OF_PLANE_ROTATION],
    "Bolt2": [BACKGROUND_CLUTTER, DEFORMATION],
    "Box": [
        BACKGROUND_CLUTTER,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Boy": [
        FAST_MOTION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Car1": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        LOW_RESOLUTION,
        MOTION_BLUR,
        SCALE_VARIATION,
    ],
    "Car2": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        MOTION_BLUR,
        SCALE_VARIATION,
    ],
    "Car24": [BACKGROUND_CLUTTER, ILLUMINATION_VARIATION, SCALE_VARIATION],
    "Car4": [ILLUMINATION_VARIATION, SCALE_VARIATION],
    "CarDark": [BACKGROUND_CLUTTER, ILLUMINATION_VARIATION],
    "CarScale": [
        FAST_MOTION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "ClifBar": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Coke": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Couple": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        FAST_MOTION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Coupon": [BACKGROUND_CLUTTER, OCCLUSION],
    "Crossing": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        FAST_MOTION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Crowds": [BACKGROUND_CLUTTER, DEFORMATION, ILLUMINATION_VARIATION],
    "Dancer": [
        DEFORMATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Dancer2": [DEFORMATION],
    "David": [
        DEFORMATION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "David2": [IN_PLANE_ROTATION, OUT_OF_PLANE_ROTATION],
    "David3": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Deer": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        MOTION_BLUR,
    ],
    "Diving": [DEFORMATION, IN_PLANE_ROTATION, SCALE_VARIATION],
    "Dog": [DEFORMATION, OUT_OF_PLANE_ROTATION, SCALE_VARIATION],
    "Dog1": [IN_PLANE_ROTATION, OUT_OF_PLANE_ROTATION, SCALE_VARIATION],
    "Doll": [
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "DragonBaby": [
        FAST_MOTION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Dudek": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "FaceOcc1": [OCCLUSION],
    "FaceOcc2": [
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Fish": [ILLUMINATION_VARIATION],
    "FleetFace": [
        DEFORMATION,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Football": [
        BACKGROUND_CLUTTER,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Football1": [BACKGROUND_CLUTTER, IN_PLANE_ROTATION, OUT_OF_PLANE_ROTATION],
    "Freeman1": [IN_PLANE_ROTATION, OUT_OF_PLANE_ROTATION, SCALE_VARIATION],
    "Freeman3": [IN_PLANE_ROTATION, OUT_OF_PLANE_ROTATION, SCALE_VARIATION],
    "Freeman4": [
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Girl": [
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Girl2": [
        DEFORMATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Gym": [
        DEFORMATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Human2": [
        ILLUMINATION_VARIATION,
        MOTION_BLUR,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Human3": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Human4": [DEFORMATION, ILLUMINATION_VARIATION, OCCLUSION, SCALE_VARIATION],
    "Human5": [DEFORMATION, OCCLUSION, SCALE_VARIATION],
    "Human6": [
        DEFORMATION,
        FAST_MOTION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Human7": [
        DEFORMATION,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        MOTION_BLUR,
        OCCLUSION,
        SCALE_VARIATION,
    ],
    "Human8": [DEFORMATION, ILLUMINATION_VARIATION, SCALE_VARIATION],
    "Human9": [
        DEFORMATION,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        MOTION_BLUR,
        SCALE_VARIATION,
    ],
    "Ironman": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Jogging": [DEFORMATION, OCCLUSION, OUT_OF_PLANE_ROTATION],
    "Jump": [
        DEFORMATION,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Jumping": [FAST_MOTION, MOTION_BLUR],
    "KiteSurf": [
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Lemming": [
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Liquor": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "Man": [ILLUMINATION_VARIATION],
    "Matrix": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Mhyang": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        ILLUMINATION_VARIATION,
        OUT_OF_PLANE_ROTATION,
    ],
    "MotorRolling": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        MOTION_BLUR,
        SCALE_VARIATION,
    ],
    "MountainBike": [
        BACKGROUND_CLUTTER,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Panda": [
        DEFORMATION,
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
        SCALE_VARIATION,
    ],
    "RedTeam": [
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Rubik": [
        IN_PLANE_ROTATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Shaking": [
        BACKGROUND_CLUTTER,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Singer1": [
        ILLUMINATION_VARIATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Singer2": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Skater": [
        DEFORMATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Skater2": [
        DEFORMATION,
        FAST_MOTION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Skating1": [
        BACKGROUND_CLUTTER,
        DEFORMATION,
        ILLUMINATION_VARIATION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Skating2": [
        DEFORMATION,
        FAST_MOTION,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Skiing": [
        DEFORMATION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Soccer": [
        BACKGROUND_CLUTTER,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Subway": [BACKGROUND_CLUTTER, DEFORMATION, OCCLUSION],
    "Surfer": [
        FAST_MOTION,
        IN_PLANE_ROTATION,
        LOW_RESOLUTION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Suv": [IN_PLANE_ROTATION, OCCLUSION, OUT_OF_VIEW],
    "Sylvester": [
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Tiger1": [
        DEFORMATION,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
    ],
    "Tiger2": [
        DEFORMATION,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        OUT_OF_VIEW,
    ],
    "Toy": [
        FAST_MOTION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Trans": [DEFORMATION, ILLUMINATION_VARIATION, OCCLUSION, SCALE_VARIATION],
    "Trellis": [
        BACKGROUND_CLUTTER,
        ILLUMINATION_VARIATION,
        IN_PLANE_ROTATION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
    "Twinnings": [OUT_OF_PLANE_ROTATION, SCALE_VARIATION],
    "Vase": [FAST_MOTION, IN_PLANE_ROTATION, SCALE_VARIATION],
    "Walking": [DEFORMATION, OCCLUSION, SCALE_VARIATION],
    "Walking2": [LOW_RESOLUTION, OCCLUSION, SCALE_VARIATION],
    "Woman": [
        DEFORMATION,
        FAST_MOTION,
        ILLUMINATION_VARIATION,
        MOTION_BLUR,
        OCCLUSION,
        OUT_OF_PLANE_ROTATION,
        SCALE_VARIATION,
    ],
}


def _parse_arguments():
    parser = argparse.ArgumentParser(description="Download OTB data sequences.")
    parser.add_argument(
        "--version",
        action="version",
        version=__version__,
        help="Display the version, and exit.",
    )
    parser.parse_args()


def _clean_duplicate_sequences(root_directory):
    for sequence in ["Jogging", "Skating2"]:
        shutil.copytree(
            os.path.join(root_directory, sequence),
            os.path.join(root_directory, f"{sequence}-2"),
        )
        os.rename(
            os.path.join(root_directory, sequence),
            os.path.join(root_directory, f"{sequence}-1"),
        )
        os.rename(
            os.path.join(
                root_directory, f"{sequence}-1", "groundtruth_rect.1.txt"
            ),
            os.path.join(
                root_directory, f"{sequence}-1", "groundtruth_rect.txt"
            ),
        )
        os.rename(
            os.path.join(
                root_directory, f"{sequence}-2", "groundtruth_rect.2.txt"
            ),
            os.path.join(
                root_directory, f"{sequence}-2", "groundtruth_rect.txt"
            ),
        )
        os.remove(
            os.path.join(
                root_directory, f"{sequence}-1", "groundtruth_rect.2.txt"
            )
        )
        os.remove(
            os.path.join(
                root_directory, f"{sequence}-2", "groundtruth_rect.1.txt"
            )
        )


def _main():
    root_directory = os.path.expanduser("~/Videos/otb")
    _parse_arguments()
    for sequence in SEQUENCES:
        print("Downloading", sequence)
        zip_file = os.path.join(root_directory, f"{sequence}.zip")
        wget.download(
            f"http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/{sequence}.zip",
            zip_file,
        )
        print()
        with zipfile.ZipFile(zip_file) as file_:
            file_.extractall(path=root_directory)
        os.remove(zip_file)
        with open(
            os.path.join(root_directory, sequence, "attributes.txt"), "w"
        ) as file_:
            for attribute in SEQUENCES[sequence]:
                file_.write(f"{attribute}\n")
    _clean_duplicate_sequences(root_directory)
    shutil.rmtree(os.path.join(root_directory, "__MACOSX"))


if __name__ == "__main__":
    _main()
