#!/usr/bin/env python3

"""This is a script to download OTB data sets."""

import argparse
import os.path
import zipfile

import wget

__version__ = "1.0"


SEQUENCES = [
    "Basketball",
    "Biker",
    "Bird1",
    "Bird2",
    "BlurBody",
    "BlurCar1",
    "BlurCar2",
    "BlurCar3",
    "BlurCar4",
    "BlurFace",
    "BlurOwl",
    "Board",
    "Bolt",
    "Bolt2",
    "Box",
    "Boy",
    "Car1",
    "Car2",
    "Car24",
    "Car4",
    "CarDark",
    "CarScale",
    "ClifBar",
    "Coke",
    "Couple",
    "Coupon",
    "Crossing",
    "Crowds",
    "Dancer",
    "Dancer2",
    "David",
    "David2",
    "David3",
    "Deer",
    "Diving",
    "Dog",
    "Dog1",
    "Doll",
    "DragonBaby",
    "Dudek",
    "FaceOcc1",
    "FaceOcc2",
    "Fish",
    "FleetFace",
    "Football",
    "Football1",
    "Freeman1",
    "Freeman3",
    "Freeman4",
    "Girl",
    "Girl2",
    "Gym",
    "Human2",
    "Human3",
    "Human4",
    "Human5",
    "Human6",
    "Human7",
    "Human8",
    "Human9",
    "Ironman",
    "Jogging",
    "Jump",
    "Jumping",
    "KiteSurf",
    "Lemming",
    "Liquor",
    "Man",
    "Matrix",
    "Mhyang",
    "MotorRolling",
    "MountainBike",
    "Panda",
    "RedTeam",
    "Rubik",
    "Shaking",
    "Singer1",
    "Singer2",
    "Skater",
    "Skater2",
    "Skating1",
    "Skating2",
    "Skiing",
    "Soccer",
    "Subway",
    "Surfer",
    "Suv",
    "Sylvester",
    "Tiger1",
    "Tiger2",
    "Toy",
    "Trans",
    "Trellis",
    "Twinnings",
    "Vase",
    "Walking",
    "Walking2",
    "Woman",
]


def _parse_arguments():
    parser = argparse.ArgumentParser(description="Download OTB data sequences.")
    parser.add_argument(
        "--version",
        action="version",
        version=__version__,
        help="Display the version, and exit.",
    )
    parser.parse_args()


def _main():
    root_directory = os.path.expanduser("~/Videos/otb")
    _parse_arguments()
    # for sequence in SEQUENCES:
    for sequence in ["Basketball"]:
        print("Downloading", sequence)
        zip_file = os.path.join(root_directory, f"{sequence}.zip")
        wget.download(
            f"http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/{sequence}.zip",
            zip_file,
        )
        print()
        with zipfile.ZipFile(zip_file) as file_:
            file_.extractall(path=root_directory)
        os.remove(zip_file)


if __name__ == "__main__":
    _main()
